### ISSUE TITLE
Style are not used - if Statement wrong

### ISSUE THREAD

**Issue by ghost** [w3scout/contao-dompdf-bundle#2]
Hi w3scout, 
we installed your bundle with Contao Manager. We tried to figure out, why it doesn't use our Style sheets. The problem is that variable `strStyle` is not defined only `strStyles` with a s.

https://github.com/w3scout/contao-dompdf-bundle/blob/9ed2b5675d5801fe12da9efea169dc4e95dccdbf/src/Resources/contao/DompdfIgniter.php#L103

Also GitHub and Contao Manager packages are different on that line. Our installed version only has `!empty` condition.

**Comment by w3scout** [comment]
Thanks for the hint.
Fixed: https://github.com/w3scout/contao-dompdf-bundle/commit/f24dfc3b0df5eaf6cac9060d6254ffceb0433dfc

There´s a new release, please update via Contao-Manager:
https://github.com/w3scout/contao-dompdf-bundle/releases/tag/1.0.3
