### ISSUE TITLE
External stylesheets not supported?

### ISSUE THREAD

**Issue by kiparski-lumas-consulting** [w3scout/contao-dompdf-bundle#8]
Does this extension support @media print CSS rules from external stylesheets loaded via the page layout? The CSS rules are not being applied after enabling dompdf in the system settings.

**Comment by w3scout** [comment]
This package will no longer be maintained.

Contao has its own PDF library for printing articles and pages: https://extensions.contao.org/?q=tc&pages=1&p=contao%2Ftcpdf-bundle
If you need more options, you can use e.g. https://packagist.org/packages/heimrichhannot/contao-pdf-creator-bundle.

To develop your own bundles, DomPDF can be installed via Composer: https://packagist.org/packages/dompdf/dompdf
